Vagrant.configure("2") do |config|
  # Máquina Ubuntu
  config.vm.define "maquina_ubuntu" do |maquina_ubuntu|
    maquina_ubuntu.vm.box = "ubuntu/focal64"
    maquina_ubuntu.vm.network "private_network", ip: "10.0.0.30"
    maquina_ubuntu.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
    end
    maquina_ubuntu.vm.provision "shell", inline: <<-SHELL
      apt-get upgrade
    SHELL
  end
end
